name: Flutter Workflow

on: [push, workflow_dispatch]
jobs:        
  java_test:
    name: Run java tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
        
      - name: Run tests
        run: cd ai-story-generation-app && mvn --batch-mode --update-snapshots package
