name: Flutter Workflow

on: [push, workflow_dispatch]
jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v1
        with: 
          channel: "stable"
      - name: Install and test
      - working-directory: ./magic-pages-app/magic_pages
      - run: flutter pub get
      - run: flutter test
      
